#!/bin/bash

echo "🔐 Agency Admin Login Helper"
echo "=========================="
echo ""
echo "The agency admin (access@seowerks.ai) can log in using:"
echo ""
echo "1. Direct Login URL (easiest):"
echo "   https://rylie-seo-hub.onrender.com/api/auth/simple-signin?email=access@seowerks.ai"
echo ""
echo "2. Emergency Access (if configured):"
echo "   https://rylie-seo-hub.onrender.com/auth/emergency-access"
echo "   Email: access@seowerks.ai"
echo "   Token: [needs to be set in the database]"
echo ""
echo "3. Google OAuth (if the email has a Google account):"
echo "   https://rylie-seo-hub.onrender.com/auth/signin"
echo "   Click 'Sign in with Google'"
echo ""
echo "📝 Note: The simple signin method doesn't require a password."
echo "   It's designed for quick access during development/testing."
echo ""
echo "⚠️  For production, consider implementing proper authentication"
echo "   with passwords or OAuth only."
