// Debug script to check GA4 connection status
// Run this to diagnose the reporting issue

console.log('🔍 GA4 Debug Script - Checking connection status...')
console.log('📍 Visit these URLs in your browser while logged in:')
console.log('')
console.log('1️⃣ Check GA4 Connection Status:')
console.log('   https://rylie-seo-hub.onrender.com/api/ga4/status')
console.log('')
console.log('2️⃣ Test GA4 Analytics API:')
console.log('   https://rylie-seo-hub.onrender.com/api/debug/test-ga4-analytics')
console.log('')
console.log('3️⃣ Check Current Date:')
console.log('   https://rylie-seo-hub.onrender.com/api/debug/current-date')
console.log('')
console.log('4️⃣ Test Historical GA4 Data:')
console.log('   https://rylie-seo-hub.onrender.com/api/debug/test-historical-ga4')
console.log('')
console.log('📋 Expected Results:')
console.log('  ✅ Status: connected: true, propertyId: "123456789"')
console.log('  ✅ Analytics Test: success: true, reportRowCount: > 0')
console.log('  ❌ Error: "No GA4 connection found" = Need to connect GA4')
console.log('  ❌ Error: "GA4 not connected" = Missing property ID')
console.log('  ❌ Error: token expired = Need to refresh connection')
console.log('')
console.log('🔧 If GA4 is not connected, go to:')
console.log('   https://rylie-seo-hub.onrender.com/settings/ga4')
console.log('')
console.log('⚡ Run this script: node debug-ga4.js')